import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "Demo LAAS",
  description: "Generated by Adrien",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased bg-current h-screen`}
      >
        {children}
      </body>
    </html>
  );
}
